"""descrição da migração

Revision ID: 86fed64b3452
Revises: 
Create Date: 2025-04-19 14:19:18.862724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '86fed64b3452'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'cpf',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Float(),
               nullable=False)
    op.add_column('representative', sa.Column('password', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('representative', 'password')
    op.alter_column('clients', 'cpf',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
