      tags:
        - Product Filter
      summary: Cria um novo filtro de produto
      description: Endpoint protegido por JWT para cadastrar um filtro associado a um produto existente.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - filter_name
                - product_id
              properties:
                filter_name:
                  type: string
                  example: "Cor"
                product_id:
                  type: integer
                  example: 1
      responses:
        '200':
          description: Filtro de produto cadastrado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Successfully registered product filter
        '400':
          description: Erro de validação ou produto inexistente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  error:
                    type: string
                    example: "Missing field: filter_name"
        '401':
          description: Token JWT ausente ou inválido
