tags:
  - Product
summary: "Endpoint para obter os detalhes de um produto pelo ID."
description: "Este endpoint permite consultar os detalhes de um produto específico pelo seu ID."
parameters:
  - name: "id"
    in: "path"
    required: true
    type: "integer"
    description: "ID do produto a ser consultado"
    example: 1
responses:
  200:
    description: "Produto encontrado com sucesso."
    examples:
      application/json:
        status: 200
        data:
          id: 1
          name: "Produto A"
          price: 99.99
          description: "Descrição do Produto A"
  401:
    description: "Token de autenticação inválido ou ausente."
    examples:
      application/json:
        status: 401
        message: "Token de autenticação ausente ou inválido."
  404:
    description: "Produto não encontrado."
    examples:
      application/json:
        status: 404
        error: "Produto não encontrado"
