tags:
  - Product
summary: "Endpoint para obter uma lista de todos os produtos."
description: "Este endpoint permite obter todos os produtos registrados no sistema."
responses:
  200:
    description: "Lista de produtos retornada com sucesso."
    examples:
      application/json:
        status: 200
        data:
          - id: 1
            name: "Produto A"
            price: 99.99
            description: "Descrição do Produto A"
          - id: 2
            name: "Produto B"
            price: 150.75
            description: "Descrição do Produto B"
  401:
    description: "Token de autenticação inválido ou ausente."
    examples:
      application/json:
        status: 401
        message: "Token de autenticação ausente ou inválido."
